package com.sjjybsgj.dao.jobinfo.mapper;

import com.sjjybsgj.dao.jobinfo.model.Jobinfo;
import com.sjjybsgj.dao.jobinfo.model.JobinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JobinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobinfo
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    long countByExample(JobinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobinfo
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    int deleteByExample(JobinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobinfo
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    int insert(Jobinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobinfo
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    int insertSelective(Jobinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobinfo
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    List<Jobinfo> selectByExample(JobinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobinfo
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") Jobinfo record, @Param("example") JobinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobinfo
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    int updateByExample(@Param("record") Jobinfo record, @Param("example") JobinfoExample example);
}