package com.sjjybsgj.dao.jobinfo.model;

import java.io.Serializable;
import java.util.Date;

public class Jobinfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobinfo.USER_ID
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobinfo.JOB_ID
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    private String jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobinfo.USER_NAME
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobinfo.JOB_NAME
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobinfo.START_TIME
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobinfo.NOW_STAGE
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    private String nowStage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobinfo.ALL_STAGE
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    private String allStage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobinfo.END_TIME
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobinfo.IS_END
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    private String isEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobinfo.STATES
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    private Integer states;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jobinfo
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobinfo.USER_ID
     *
     * @return the value of jobinfo.USER_ID
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobinfo.USER_ID
     *
     * @param userId the value for jobinfo.USER_ID
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobinfo.JOB_ID
     *
     * @return the value of jobinfo.JOB_ID
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobinfo.JOB_ID
     *
     * @param jobId the value for jobinfo.JOB_ID
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    public void setJobId(String jobId) {
        this.jobId = jobId == null ? null : jobId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobinfo.USER_NAME
     *
     * @return the value of jobinfo.USER_NAME
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobinfo.USER_NAME
     *
     * @param userName the value for jobinfo.USER_NAME
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobinfo.JOB_NAME
     *
     * @return the value of jobinfo.JOB_NAME
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobinfo.JOB_NAME
     *
     * @param jobName the value for jobinfo.JOB_NAME
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobinfo.START_TIME
     *
     * @return the value of jobinfo.START_TIME
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobinfo.START_TIME
     *
     * @param startTime the value for jobinfo.START_TIME
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobinfo.NOW_STAGE
     *
     * @return the value of jobinfo.NOW_STAGE
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    public String getNowStage() {
        return nowStage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobinfo.NOW_STAGE
     *
     * @param nowStage the value for jobinfo.NOW_STAGE
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    public void setNowStage(String nowStage) {
        this.nowStage = nowStage == null ? null : nowStage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobinfo.ALL_STAGE
     *
     * @return the value of jobinfo.ALL_STAGE
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    public String getAllStage() {
        return allStage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobinfo.ALL_STAGE
     *
     * @param allStage the value for jobinfo.ALL_STAGE
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    public void setAllStage(String allStage) {
        this.allStage = allStage == null ? null : allStage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobinfo.END_TIME
     *
     * @return the value of jobinfo.END_TIME
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobinfo.END_TIME
     *
     * @param endTime the value for jobinfo.END_TIME
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobinfo.IS_END
     *
     * @return the value of jobinfo.IS_END
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    public String getIsEnd() {
        return isEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobinfo.IS_END
     *
     * @param isEnd the value for jobinfo.IS_END
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    public void setIsEnd(String isEnd) {
        this.isEnd = isEnd == null ? null : isEnd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobinfo.STATES
     *
     * @return the value of jobinfo.STATES
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    public Integer getStates() {
        return states;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobinfo.STATES
     *
     * @param states the value for jobinfo.STATES
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    public void setStates(Integer states) {
        this.states = states;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobinfo
     *
     * @mbg.generated Wed May 30 21:57:09 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", jobId=").append(jobId);
        sb.append(", userName=").append(userName);
        sb.append(", jobName=").append(jobName);
        sb.append(", startTime=").append(startTime);
        sb.append(", nowStage=").append(nowStage);
        sb.append(", allStage=").append(allStage);
        sb.append(", endTime=").append(endTime);
        sb.append(", isEnd=").append(isEnd);
        sb.append(", states=").append(states);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}