package com.sjjybsgj.dao.collectrule.mapper;

import com.sjjybsgj.dao.collectrule.model.CollectRule;
import com.sjjybsgj.dao.collectrule.model.CollectRuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CollectRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_rule
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    long countByExample(CollectRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_rule
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    int deleteByExample(CollectRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_rule
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    int insert(CollectRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_rule
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    int insertSelective(CollectRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_rule
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    List<CollectRule> selectByExample(CollectRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_rule
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    int updateByExampleSelective(@Param("record") CollectRule record, @Param("example") CollectRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_rule
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    int updateByExample(@Param("record") CollectRule record, @Param("example") CollectRuleExample example);
}