package com.sjjybsgj.dao.sourcedb.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.sjjybsgj.dao.sourcedb.model.SourceDb;
import com.sjjybsgj.dao.sourcedb.model.SourceDbExample;

public interface SourceDbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    long countByExample(SourceDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    int deleteByExample(SourceDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    int deleteByPrimaryKey(String dbSourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    int insert(SourceDb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    int insertSelective(SourceDb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    List<SourceDb> selectByExample(SourceDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    SourceDb selectByPrimaryKey(String dbSourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") SourceDb record, @Param("example") SourceDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    int updateByExample(@Param("record") SourceDb record, @Param("example") SourceDbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    int updateByPrimaryKeySelective(SourceDb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    int updateByPrimaryKey(SourceDb record);
}