package com.sjjybsgj.dao.collectrule.model;

import java.io.Serializable;

public class CollectRule implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_rule.COLLECT_ID
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    private String collectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_rule.DB_NAME
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    private String dbName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_rule.COLLECT_NAME
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    private String collectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_rule.COLLECT_INFO
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    private String collectInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_rule.COLLECT_SQL
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    private String collectSql;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table collect_rule
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_rule.COLLECT_ID
     *
     * @return the value of collect_rule.COLLECT_ID
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    public String getCollectId() {
        return collectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_rule.COLLECT_ID
     *
     * @param collectId the value for collect_rule.COLLECT_ID
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    public void setCollectId(String collectId) {
        this.collectId = collectId == null ? null : collectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_rule.DB_NAME
     *
     * @return the value of collect_rule.DB_NAME
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    public String getDbName() {
        return dbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_rule.DB_NAME
     *
     * @param dbName the value for collect_rule.DB_NAME
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    public void setDbName(String dbName) {
        this.dbName = dbName == null ? null : dbName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_rule.COLLECT_NAME
     *
     * @return the value of collect_rule.COLLECT_NAME
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    public String getCollectName() {
        return collectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_rule.COLLECT_NAME
     *
     * @param collectName the value for collect_rule.COLLECT_NAME
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    public void setCollectName(String collectName) {
        this.collectName = collectName == null ? null : collectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_rule.COLLECT_INFO
     *
     * @return the value of collect_rule.COLLECT_INFO
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    public String getCollectInfo() {
        return collectInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_rule.COLLECT_INFO
     *
     * @param collectInfo the value for collect_rule.COLLECT_INFO
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    public void setCollectInfo(String collectInfo) {
        this.collectInfo = collectInfo == null ? null : collectInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_rule.COLLECT_SQL
     *
     * @return the value of collect_rule.COLLECT_SQL
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    public String getCollectSql() {
        return collectSql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_rule.COLLECT_SQL
     *
     * @param collectSql the value for collect_rule.COLLECT_SQL
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    public void setCollectSql(String collectSql) {
        this.collectSql = collectSql == null ? null : collectSql.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_rule
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", collectId=").append(collectId);
        sb.append(", dbName=").append(dbName);
        sb.append(", collectName=").append(collectName);
        sb.append(", collectInfo=").append(collectInfo);
        sb.append(", collectSql=").append(collectSql);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}