package com.sjjybsgj.dao.collectrule.model;

import java.util.ArrayList;
import java.util.List;

public class CollectRuleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table collect_rule
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table collect_rule
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table collect_rule
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_rule
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    public CollectRuleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_rule
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_rule
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_rule
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_rule
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_rule
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_rule
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_rule
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_rule
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_rule
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_rule
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table collect_rule
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCollectIdIsNull() {
            addCriterion("COLLECT_ID is null");
            return (Criteria) this;
        }

        public Criteria andCollectIdIsNotNull() {
            addCriterion("COLLECT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCollectIdEqualTo(String value) {
            addCriterion("COLLECT_ID =", value, "collectId");
            return (Criteria) this;
        }

        public Criteria andCollectIdNotEqualTo(String value) {
            addCriterion("COLLECT_ID <>", value, "collectId");
            return (Criteria) this;
        }

        public Criteria andCollectIdGreaterThan(String value) {
            addCriterion("COLLECT_ID >", value, "collectId");
            return (Criteria) this;
        }

        public Criteria andCollectIdGreaterThanOrEqualTo(String value) {
            addCriterion("COLLECT_ID >=", value, "collectId");
            return (Criteria) this;
        }

        public Criteria andCollectIdLessThan(String value) {
            addCriterion("COLLECT_ID <", value, "collectId");
            return (Criteria) this;
        }

        public Criteria andCollectIdLessThanOrEqualTo(String value) {
            addCriterion("COLLECT_ID <=", value, "collectId");
            return (Criteria) this;
        }

        public Criteria andCollectIdLike(String value) {
            addCriterion("COLLECT_ID like", value, "collectId");
            return (Criteria) this;
        }

        public Criteria andCollectIdNotLike(String value) {
            addCriterion("COLLECT_ID not like", value, "collectId");
            return (Criteria) this;
        }

        public Criteria andCollectIdIn(List<String> values) {
            addCriterion("COLLECT_ID in", values, "collectId");
            return (Criteria) this;
        }

        public Criteria andCollectIdNotIn(List<String> values) {
            addCriterion("COLLECT_ID not in", values, "collectId");
            return (Criteria) this;
        }

        public Criteria andCollectIdBetween(String value1, String value2) {
            addCriterion("COLLECT_ID between", value1, value2, "collectId");
            return (Criteria) this;
        }

        public Criteria andCollectIdNotBetween(String value1, String value2) {
            addCriterion("COLLECT_ID not between", value1, value2, "collectId");
            return (Criteria) this;
        }

        public Criteria andDbNameIsNull() {
            addCriterion("DB_NAME is null");
            return (Criteria) this;
        }

        public Criteria andDbNameIsNotNull() {
            addCriterion("DB_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andDbNameEqualTo(String value) {
            addCriterion("DB_NAME =", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameNotEqualTo(String value) {
            addCriterion("DB_NAME <>", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameGreaterThan(String value) {
            addCriterion("DB_NAME >", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameGreaterThanOrEqualTo(String value) {
            addCriterion("DB_NAME >=", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameLessThan(String value) {
            addCriterion("DB_NAME <", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameLessThanOrEqualTo(String value) {
            addCriterion("DB_NAME <=", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameLike(String value) {
            addCriterion("DB_NAME like", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameNotLike(String value) {
            addCriterion("DB_NAME not like", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameIn(List<String> values) {
            addCriterion("DB_NAME in", values, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameNotIn(List<String> values) {
            addCriterion("DB_NAME not in", values, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameBetween(String value1, String value2) {
            addCriterion("DB_NAME between", value1, value2, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameNotBetween(String value1, String value2) {
            addCriterion("DB_NAME not between", value1, value2, "dbName");
            return (Criteria) this;
        }

        public Criteria andCollectNameIsNull() {
            addCriterion("COLLECT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCollectNameIsNotNull() {
            addCriterion("COLLECT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCollectNameEqualTo(String value) {
            addCriterion("COLLECT_NAME =", value, "collectName");
            return (Criteria) this;
        }

        public Criteria andCollectNameNotEqualTo(String value) {
            addCriterion("COLLECT_NAME <>", value, "collectName");
            return (Criteria) this;
        }

        public Criteria andCollectNameGreaterThan(String value) {
            addCriterion("COLLECT_NAME >", value, "collectName");
            return (Criteria) this;
        }

        public Criteria andCollectNameGreaterThanOrEqualTo(String value) {
            addCriterion("COLLECT_NAME >=", value, "collectName");
            return (Criteria) this;
        }

        public Criteria andCollectNameLessThan(String value) {
            addCriterion("COLLECT_NAME <", value, "collectName");
            return (Criteria) this;
        }

        public Criteria andCollectNameLessThanOrEqualTo(String value) {
            addCriterion("COLLECT_NAME <=", value, "collectName");
            return (Criteria) this;
        }

        public Criteria andCollectNameLike(String value) {
            addCriterion("COLLECT_NAME like", value, "collectName");
            return (Criteria) this;
        }

        public Criteria andCollectNameNotLike(String value) {
            addCriterion("COLLECT_NAME not like", value, "collectName");
            return (Criteria) this;
        }

        public Criteria andCollectNameIn(List<String> values) {
            addCriterion("COLLECT_NAME in", values, "collectName");
            return (Criteria) this;
        }

        public Criteria andCollectNameNotIn(List<String> values) {
            addCriterion("COLLECT_NAME not in", values, "collectName");
            return (Criteria) this;
        }

        public Criteria andCollectNameBetween(String value1, String value2) {
            addCriterion("COLLECT_NAME between", value1, value2, "collectName");
            return (Criteria) this;
        }

        public Criteria andCollectNameNotBetween(String value1, String value2) {
            addCriterion("COLLECT_NAME not between", value1, value2, "collectName");
            return (Criteria) this;
        }

        public Criteria andCollectInfoIsNull() {
            addCriterion("COLLECT_INFO is null");
            return (Criteria) this;
        }

        public Criteria andCollectInfoIsNotNull() {
            addCriterion("COLLECT_INFO is not null");
            return (Criteria) this;
        }

        public Criteria andCollectInfoEqualTo(String value) {
            addCriterion("COLLECT_INFO =", value, "collectInfo");
            return (Criteria) this;
        }

        public Criteria andCollectInfoNotEqualTo(String value) {
            addCriterion("COLLECT_INFO <>", value, "collectInfo");
            return (Criteria) this;
        }

        public Criteria andCollectInfoGreaterThan(String value) {
            addCriterion("COLLECT_INFO >", value, "collectInfo");
            return (Criteria) this;
        }

        public Criteria andCollectInfoGreaterThanOrEqualTo(String value) {
            addCriterion("COLLECT_INFO >=", value, "collectInfo");
            return (Criteria) this;
        }

        public Criteria andCollectInfoLessThan(String value) {
            addCriterion("COLLECT_INFO <", value, "collectInfo");
            return (Criteria) this;
        }

        public Criteria andCollectInfoLessThanOrEqualTo(String value) {
            addCriterion("COLLECT_INFO <=", value, "collectInfo");
            return (Criteria) this;
        }

        public Criteria andCollectInfoLike(String value) {
            addCriterion("COLLECT_INFO like", value, "collectInfo");
            return (Criteria) this;
        }

        public Criteria andCollectInfoNotLike(String value) {
            addCriterion("COLLECT_INFO not like", value, "collectInfo");
            return (Criteria) this;
        }

        public Criteria andCollectInfoIn(List<String> values) {
            addCriterion("COLLECT_INFO in", values, "collectInfo");
            return (Criteria) this;
        }

        public Criteria andCollectInfoNotIn(List<String> values) {
            addCriterion("COLLECT_INFO not in", values, "collectInfo");
            return (Criteria) this;
        }

        public Criteria andCollectInfoBetween(String value1, String value2) {
            addCriterion("COLLECT_INFO between", value1, value2, "collectInfo");
            return (Criteria) this;
        }

        public Criteria andCollectInfoNotBetween(String value1, String value2) {
            addCriterion("COLLECT_INFO not between", value1, value2, "collectInfo");
            return (Criteria) this;
        }

        public Criteria andCollectSqlIsNull() {
            addCriterion("COLLECT_SQL is null");
            return (Criteria) this;
        }

        public Criteria andCollectSqlIsNotNull() {
            addCriterion("COLLECT_SQL is not null");
            return (Criteria) this;
        }

        public Criteria andCollectSqlEqualTo(String value) {
            addCriterion("COLLECT_SQL =", value, "collectSql");
            return (Criteria) this;
        }

        public Criteria andCollectSqlNotEqualTo(String value) {
            addCriterion("COLLECT_SQL <>", value, "collectSql");
            return (Criteria) this;
        }

        public Criteria andCollectSqlGreaterThan(String value) {
            addCriterion("COLLECT_SQL >", value, "collectSql");
            return (Criteria) this;
        }

        public Criteria andCollectSqlGreaterThanOrEqualTo(String value) {
            addCriterion("COLLECT_SQL >=", value, "collectSql");
            return (Criteria) this;
        }

        public Criteria andCollectSqlLessThan(String value) {
            addCriterion("COLLECT_SQL <", value, "collectSql");
            return (Criteria) this;
        }

        public Criteria andCollectSqlLessThanOrEqualTo(String value) {
            addCriterion("COLLECT_SQL <=", value, "collectSql");
            return (Criteria) this;
        }

        public Criteria andCollectSqlLike(String value) {
            addCriterion("COLLECT_SQL like", value, "collectSql");
            return (Criteria) this;
        }

        public Criteria andCollectSqlNotLike(String value) {
            addCriterion("COLLECT_SQL not like", value, "collectSql");
            return (Criteria) this;
        }

        public Criteria andCollectSqlIn(List<String> values) {
            addCriterion("COLLECT_SQL in", values, "collectSql");
            return (Criteria) this;
        }

        public Criteria andCollectSqlNotIn(List<String> values) {
            addCriterion("COLLECT_SQL not in", values, "collectSql");
            return (Criteria) this;
        }

        public Criteria andCollectSqlBetween(String value1, String value2) {
            addCriterion("COLLECT_SQL between", value1, value2, "collectSql");
            return (Criteria) this;
        }

        public Criteria andCollectSqlNotBetween(String value1, String value2) {
            addCriterion("COLLECT_SQL not between", value1, value2, "collectSql");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table collect_rule
     *
     * @mbg.generated do_not_delete_during_merge Wed May 30 17:55:59 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table collect_rule
     *
     * @mbg.generated Wed May 30 17:55:59 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}